
trigger:
- main

pool:
  name: myWindowsAgent

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: a8108c2b-496c-424d-8347-ecc8afb6384c
    ScriptType: 'FilePath'
    ScriptPath: './ScriptAz.ps1'
    ScriptArguments: -ResourceGroupName RsGroupOG -TemplateFile .\finalTemplate.json
    azurePowerShellVersion: 'LatestVersion'
